menthorship/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
  path('create/<int:mentor_id>', views.create_booking, name='create_booking'),
  path('reject/<int:booking_id>', views.reject_booking, name='reject_booking'),
  path('cancel/<int:booking_id>', views.cancel_booking, name='cancel_booking'),
  path('accept/<int:booking_id>', views.accept_booking, name='accept_booking')
]

menthorship/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout_view'),
]

menthorship/menthorship/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('oleh/', include('oleh.urls')),
    path('', include('main.urls')),
    path('mentor/', include('mentor.urls')),
    path('booking/', include('booking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menthorship/mentor/urls.py
from django.urls import path
from . import views

app_name = 'mentor'

urlpatterns = [
    path('mentor/<int:mentor_id>', views.show_mentor, name='show_mentor'),
    path('show_all', views.show_mentors, name='show_mentors'),
    path('delete/<int:mentor_id>', views.delete_mentor, name='delete_mentor'),
    path('edit_mentor/<int:mentor_id>', views.edit_mentor, name='edit_mentor'),
    path('add_mentor', views.add_mentor, name='add_mentor'),
    path('intake_mentor',views.intake_mentor, name='intake_mentor'),
    path('dashboard/<int:mentor_id>',views.dashboard, name='dashboard'),
]

menthorship/mentor/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Language, Location


class Mentor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, default=None, null=True)
    status = models.BooleanField(default=False)
    description = models.TextField(null=True, default=None)
    picture = models.ImageField(upload_to='images', null=True)
    languages = models.ManyToManyField(Language)

    def __str__(self):
        return "{}".format(self.user)

menthorship/mentor/forms.py
from django.forms import ModelForm
from .models import Mentor
from booking.models import Booking


class MentorForm(ModelForm):
    class Meta:
        model = Mentor
        fields = '__all__'


class MentorIntakeForm(ModelForm):
    class Meta:
        model = Mentor
        fields = ['location', 'description', 'picture', 'languages']
        

menthorship/mentor/views.py
from django.shortcuts import render, redirect
from .models import Mentor
from booking.models import Booking
from .forms import MentorForm, MentorIntakeForm
from booking.views import *


def show_mentor(request, mentor_id):
    mentor = Mentor.objects.get(pk=mentor_id)
    return render(request, 'mentor_dashboard.html', {
        'mentor': mentor
    })
              
def show_mentors(request):
    mentors = Mentor.objects.all()
    return render(request, 'mentors.html', {
        'mentor': mentors
    })              

def delete_mentor(request, mentor_id):
    mentor = Mentor.objects.get(pk=mentor_id).delete()
    return redirect('mentor:show_mentors')
    
def add_mentor(request):
    form = MentorForm()
    if request.method == 'POST':
        form = MentorForm(request.POST, request.FILES, instance=mentor)
        if form.is_valid():
            form.save()
            return redirect('mentor:show_mentors')
    return render(request, 'add_mentor.html', {
        'form': form
    })
    
def edit_mentor(request, mentor_id):
    mentor = Mentor.objects.get(pk=mentor_id)
    form = MentorForm(instance=mentor)
    if request.method == 'POST':
        form = MentorForm(request.POST, request.FILES, instance=mentor)
        if form.is_valid():
            form.save()
            return redirect('mentor:show_mentor', mentor_id=mentor_id)
    return render(request, 'edit_mentor.html', {
        'mentor': mentor,
        'form': form
    })

def intake_mentor(request):
    mentor = request.user.mentor
    form = MentorIntakeForm(instance=mentor)
    if request.method == "POST":
        form = MentorIntakeForm(request.POST, request.FILES, instance=mentor)
        if form.is_valid():
            form.save()
        return redirect('mentor:show_mentor', mentor_id=mentor.id)
    return render(request, 'intake_mentor.html', {
        'mentor': mentor,
        'form': form
    })

def dashboard(request, mentor_id):
    mentor = Mentor.objects.get(pk=mentor_id)
    bookings = Booking.objects.filter(mentor_id=mentor.id)
    return render(request, 'mentor_dashboard.html', {
        'mentor': mentor,
        'bookings': bookings
    })

menthorship/mentor/templates/intake_mentor.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Intake{% endblock %}
{% block content %}
<div class='container mx-auto'>
  <div class='row'>
    <div class='col-md-12'>
      <form method="POST">
      	{% csrf_token %}
      	{{ form | crispy}}
      	<button type="submit">Submit</button>
      </form>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-8'>
      <div class="alert alert-success">
        <strong>Success!</strong>
      </div>
    </div>
  </div>
</div>

{% endblock %}

menthorship/mentor/templates/mentor_dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <div class='container mx-auto'>
      <div class='row'>
        <div class='col-md-3'>
          <div class="card align-items-center">
            <img src="/media/{{ mentor.picture }}" style="width: 250px" class="rounded-circle" alt="Cinque Terre">
            <div class="card-body">
              <dl>
                <dt>Name</dt>
                <dd>{{user}}</dd>
                <dt>Languages</dt>
                <dd>{{mentor.languages}}</dd>
                <dt>Location</dt>
                <dd>{{mentor.location.name}}</dd>
              </dl>
              <p class="card-text">{{mentor.description}}</p>
            </div>
          </div>
          </div>
        <div class='col-md-4'>
          {% for booking in bookings %}
          <div class="card align-items-center">
            <div class="card-body">
              <img src="/media/{{ booking.oleh.picture }}" style="width: 150px" class="rounded-circle" alt="Cinque Terre">
              <dl>
                <dd class="mt-2"><h2>{{booking.oleh}}</h2></dd>
              </dl>
              <p class="card-text">{{booking.oleh.description}}</p>
              <h5>Mentorship request</h5>
              {% if booking.status == 'accepted' %}
              <a href="" class="btn btn-primary">Connect</a>
              {% elif booking.status == 'pending' %}
              <a href="{% url 'booking:accept_booking' booking.id %}" class="btn btn-primary">Accept</a>
              <a href="" class="btn btn-primary">Reject</a>
              {% else %}
               <p>Request rejected</p>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
        <div class='col-md-5'>
          <div class="card">
            <div class="card-body">
              <div style='text-align: center; margin-top: 20px;'>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                  Add task
                </button>
              </div>
              <dl>
                <dt>Tasks:</dt>
                <dd>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque sunt possimus ipsam fugiat, illo, quos minus sapiente aliquam in debitis saepe cum sed. At ut laboriosam, nulla quidem nihil dolorum?</dd>
              </dl>
            </div>
          </div>
        </div>
      </div>
      <div class='row'>
        <div class='col-md-8 mx-auto'>
          CHAT
        </div>
      </div>
    </div>
    <div class="container">
      <!-- The Modal -->
      <div class="modal" id="myModal">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Title</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              <div class='modalBody'>
                <div class='col-md-6'>
                  <label>
                    Task:
                    <input />
                  </label>
                  <label>
                    Description:
                    <textarea></textarea>
                  </label>
                </div>
              </div>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-primary" data-dismiss="modal">Add</button>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}