menthorship/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout_view'),
]

menthorship/menthorship/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('oleh/', include('oleh.urls')),
    path('', include('main.urls')),
    path('mentor/', include('mentor.urls')),
    path('booking/', include('booking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menthorship/messaging/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


urlpatterns = [
  path('chat/<int:user_id>', views.chat, name='chat'),
  path('chatid/<int:chat_id>', views.chat_by_id, name='chat_by_id'),

]

menthorship/messaging/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Chat(models.Model):
	users = models.ManyToManyField(User)

class Message(models.Model):
	content = models.TextField(blank=True, null=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	sender = models.ForeignKey(User, on_delete=models.CASCADE)
	chat = models.ForeignKey(Chat, on_delete=models.CASCADE)

menthorship/messaging/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

# Create your views here.

def chat(request,user_id):
	user2 = User.objects.filter(pk=user_id).first()
	chat = Chat.objects.filter(users=request.user).filter(users=user2).distinct().first()

	if chat == None:
		chat = PrivateChat()
		chat.save()
		chat.users.add(request.user.profile, user2)
	if request.method == 'POST':
		message = Message(chat=chat, content=request.POST.get('content'), profile=request.user.profile)
		message.save()
	return render(request, 'chat.html', {'chat' : chat, 'user2' : user2})


def chat_by_id(request,chat_id):
	chat = Chat.objects.filter(pk=chat_id).first()
	user2 = chat.users.exclude(user=request.user).first()
	return redirect('chat', user2.id )

menthorship/messaging/templates/chat.html
{% block content %}
    <div>
      <h3 class="mt-3">{{chat.name}} Chat with your mentor {% if request.user == chat.users.last %}
        {{chat.users.first.first_name}} {{chat.users.first.last_name}}
      {% else %}
        {{chat.users.last.first_name}} {{chat.users.first.last_name}}
      {% endif %}</h3>
      <hr />
    </div>
    <div style="height: 75vh">
      <div >

        {% for message in chat.message_set.all %}
          {% if request.user == message.sender %}
            <div class="card-body bg-info p-1 m-1 rounded">
              <h6>You<cite class="text-secondary">~{{message.timestamp | timesince}} ago</cite>
              </h6>
              <p>{{message.content}}</p>
            </div>
          {% else %}
            <div class="card-body bg-secondary p-1 m-1 rounded">
              <h6>{{message.sender.first_name}} {{message.sender.last_name}} <cite class="grey-text darken-1">~{{message.timestamp | timesince}} ago</cite></h6>

              <p>{{message.content}}</p>
            </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
    <div>
      <form method="POST" class="col-12">
        {% csrf_token %}
        <div class="row">
          <div class="form-group col-11 mx-auto">

            <textarea name="content" class="form-control" id="exampleFormControlTextarea1" placeholder="Start typing your message..."></textarea>
          </div>
          <button type="submit" class="btn btn-primary mx-auto mb-3">Send</button>
        </div>
      </form>
    </div>
{% endblock %}