menthorship/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
  path('create/<int:mentor_id>', views.create_booking, name='create_booking'),
  path('reject/<int:booking_id>', views.reject_booking, name='reject_booking'),
  path('cancel/<int:booking_id>', views.cancel_booking, name='cancel_booking'),
  path('accept/<int:booking_id>', views.accept_booking, name='accept_booking')
]

menthorship/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout_view'),
]

menthorship/menthorship/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('oleh/', include('oleh.urls')),
    path('', include('main.urls')),
    path('mentor/', include('mentor.urls')),
    path('booking/', include('booking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menthorship/oleh/urls.py
from django.urls import path
from . import views

app_name = 'oleh'

urlpatterns = [
    path('oleh/<int:oleh_id>', views.show_oleh, name='show_oleh'),
    path('show_all', views.show_olehs, name='show_olehs'),
    path('delete/<int:oleh_id>', views.delete_oleh, name='delete_oleh'),
    path('edit_oleh/<int:oleh_id>', views.edit_oleh, name='edit_oleh'),
    path('add_oleh', views.add_oleh, name='add_oleh'),
    path('intake_oleh',views.intake_oleh, name='intake_oleh'),
    path('dashboard',views.dashboard, name='dashboard'),
    path('pick_mentor',views.pick_mentor, name='pick_mentor'),
]

menthorship/oleh/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Language, Location



class Oleh(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	description = models.TextField(blank=True, null=True)
	location = models.ForeignKey(Location, on_delete=models.CASCADE, null=True)
	picture = models.ImageField(upload_to='images', null=True)
	languages = models.ManyToManyField(Language)

	def __str__(self):
		return "{}".format(self.user)


class Task(models.Model):
	oleh = models.ForeignKey(Oleh, on_delete=models.CASCADE)
	value = models.CharField(max_length=220)

menthorship/oleh/forms.py
from django.forms import ModelForm
from .models import Oleh


class OlehForm(ModelForm):
    class Meta:
        model = Oleh
        fields = '__all__'

class OlehIntakeForm(ModelForm):
    class Meta:
        model = Oleh
        fields = ['location', 'description', 'languages']

menthorship/oleh/views.py
from django.shortcuts import render, redirect
from .models import Oleh, Task
from .forms import OlehForm, OlehIntakeForm
from main.models import Event
from mentor.models import Mentor
from messaging.models import Chat, Message


def show_oleh(request, oleh_id):
    oleh = Oleh.objects.get(pk=oleh_id)
    return render(request, 'oleh.html', {
        'oleh': oleh
    })
              
def show_olehs(request):
    olehs = Oleh.objects.all()
    return render(request, 'olehs.html', {
        'oleh': olehs
    })              

def delete_oleh(request, oleh_id):
    oleh = Oleh.objects.get(pk=oleh_id).delete()
    return redirect('oleh:show_olehs')
    
def add_oleh(request):
    form = OlehForm()
    if request.method == 'POST':
        form = OlehForm(request.POST, request.FILES, instance=oleh)
        if form.is_valid():
            form.save()
            return redirect('oleh:show_olehs')
    return render(request, 'add_oleh.html', {
        'form': form
    })
    
def edit_oleh(request, oleh_id):
    oleh = Oleh.objects.get(pk=oleh_id)
    form = OlehForm(instance=oleh)
    if request.method == 'POST':
        form = OlehForm(request.POST, request.FILES, instance=oleh)
        if form.is_valid():
            form.save()
            return redirect('oleh:show_oleh', oleh_id=oleh_id)
    return render(request, 'edit_oleh.html', {
        'oleh': oleh,
        'form': form
    })

def intake_oleh(request):
  oleh = request.user.oleh
  form = OlehIntakeForm(instance=oleh)
  if request.method == "POST":
    form = OlehIntakeForm(request.POST, request.FILES, instance=oleh)
    if form.is_valid():
      form.save()
      return redirect('oleh:pick_mentor')
  return render(request, 'intake_oleh.html', {
      'oleh': oleh,
      'form': form
  })

def dashboard(request):
  chat = Chat.objects.filter(users=request.user).distinct().first()
  if request.method == "POST":
    message = Message(chat=chat, content=request.POST.get('content'), sender=request.user)
    message.save()
  events = Event.objects.filter(location=request.user.oleh.location)
  tasks = Task.objects.filter(oleh=request.user.oleh)
  return render(request, 'oleh_dashboard.html', {'events' : events, 'tasks' : tasks, 'chat' : chat})

def pick_mentor(request):
  oleh = request.user.oleh
  mentor_list = Mentor.objects.filter(languages=oleh.languages.first()).filter(location=oleh.location)
  return render(request, 'list_of_mentors.html', {'mentor_list' : mentor_list} )

menthorship/oleh/templates/intake_oleh.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class='container mx-auto'>
  <div class='row'>
    <div class='col-md-12'>
      <form method="POST">
      	{% csrf_token %}
      	{{form | crispy}}
      	<button type="submit">Submit</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

menthorship/oleh/templates/list_of_mentors.html
{% extends "base.html" %}
{% block title %}Choose your mentor{% endblock %}
{% block content %}
  <div class='container mx-auto'>
    <div class="row">
      {% for mentor in mentor_list%}
        <div class="col-md-4">
          <div class="card" style="width: 18rem;">
            <img src="https://thelogo.shop/wp-content/uploads/2016/12/03-Smiling-Face.png" class="card-img-top" alt="mentor-photo">
            <div class="card-body">
              <h5 class="card-title">{{mentor.user.first_name}} {{mentor.user.last_name}}</h5>
              <p class="card-text">{{mentor.description}}</p>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal{{mentor.id}}">
              Open modal
              </button>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- The Modal -->
          <div class="modal" id="myModal{{mentor.id}}">
            <div class="modal-dialog">
              <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                  <h4 class="modal-title">{{mentor.user.first_name}} {{mentor.user.last_name}}</h4>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                  <div class='modalBody'>
                    <div class='col-md-6'>
                      <img src="https://thelogo.shop/wp-content/uploads/2016/12/03-Smiling-Face.png" class="card-img-top" alt="mentor-photo">
                    </div>
                    <div class='col-md-6'>
                      <ul>
                        <li>
                          {{mentor.location.name}}
                        </li>
                        <li>
                          {{mentor.languages.first.name}}
                        </li>
                        <li>
                          coming soon..
                        </li>
                        <ul>
                        </div>
                      </div>
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                      <a href="{% url 'booking:create_booking' mentor.id %}" type="button" class="btn btn-primary" data-dismiss="modal">Let's Meet!</a>
                      <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    {% endblock %}

menthorship/oleh/templates/oleh_dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
{% include "navbar.html" %}

<div class='container mx-auto'>
  <div class="row justify-content-between">
    <div class="col-md-6" style="border: 1px solid lightgray; border-radius: 5px;">
      {% include "chat.html" %}
    </div>
    <div class="col-md-5 col-lg-5 float">
      <h3 class="card-title mb-3">Upcoming tasks</h3>
      {% for task in tasks %}
      <div class="card" style="width:400px">
        <div class="card-body">
          <h5 class="card-title">{{task.value}}</h5>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <hr class="mt-5">  
  <div class="row">
      {% for event in events %}
    <div class="col-md-6">
      <div class="card" style="width:500px; margin: 20px;">
        <img class="card-img-top" src="{{event.picture}}" alt="Card image">
        <div class="card-img-overlay">
          <h4 class="card-title">{{event.title}}</h4>
          <p class="card-text">{{event.datetime}}</p>
          <p class="card-text">@{{event.location.name}}</p>
          <a href="#" class="btn btn-primary">Learn more</a>
        </div>
      </div>
    </div>
      {% endfor %}
    <div class="col-md-4">

    </div>
    <div class="col-md-4">

    </div>
  </div>
</div>
{% endblock %}